import { Card, Set } from '@/types';

export const mockSets: Set[] = [
    { id: '1', name: 'Alpha Edition', icon: '🎴' },
    { id: '2', name: 'Beta Edition', icon: '🃏' },
    { id: '3', name: 'Unlimited Edition', icon: '♠️' },
    { id: '4', name: 'Revised Edition', icon: '♥️' },
    { id: '5', name: 'Modern Horizons', icon: '⚡' },
    { id: '6', name: 'Commander Legends', icon: '👑' },
];

export const mockCards: Card[] = [
    {
        id: '1',
        name: 'Black Lotus',
        set: 'Alpha Edition',
        setIcon: '🎴',
        image: '/black-lotus.png',
        cashPrice: 25000.00,
        creditPrice: 30000.00,
        rarity: 'Rare',
        cardNumber: '001',
    },
    {
        id: '2',
        name: 'Ancestral Recall',
        set: 'Alpha Edition',
        setIcon: '🎴',
        image: '/black-lotus.png',
        cashPrice: 15000.00,
        creditPrice: 18000.00,
        rarity: 'Rare',
        cardNumber: '002',
    },
    {
        id: '3',
        name: 'Time Walk',
        set: 'Alpha Edition',
        setIcon: '🎴',
        image: '/black-lotus.png',
        cashPrice: 12000.00,
        creditPrice: 14400.00,
        rarity: 'Rare',
        cardNumber: '003',
    },
    {
        id: '4',
        name: 'Mox Sapphire',
        set: 'Beta Edition',
        setIcon: '🃏',
        image: '/black-lotus.png',
        cashPrice: 8000.00,
        creditPrice: 9600.00,
        rarity: 'Rare',
        cardNumber: '004',
    },
    {
        id: '5',
        name: 'Mox Ruby',
        set: 'Beta Edition',
        setIcon: '🃏',
        image: '/black-lotus.png',
        cashPrice: 7500.00,
        creditPrice: 9000.00,
        rarity: 'Rare',
        cardNumber: '005',
    },
    {
        id: '6',
        name: 'Lightning Bolt',
        set: 'Unlimited Edition',
        setIcon: '♠️',
        image: '/charizard.png',
        cashPrice: 50.00,
        creditPrice: 60.00,
        rarity: 'Common',
        cardNumber: '006',
    },
    {
        id: '7',
        name: 'Counterspell',
        set: 'Unlimited Edition',
        setIcon: '♠️',
        image: '/blue-eyes.png',
        cashPrice: 35.00,
        creditPrice: 42.00,
        rarity: 'Common',
        cardNumber: '007',
    },
    {
        id: '8',
        name: 'Sol Ring',
        set: 'Commander Legends',
        setIcon: '👑',
        image: '/one-ring.png',
        cashPrice: 150.00,
        creditPrice: 180.00,
        rarity: 'Uncommon',
        cardNumber: '008',
    },
];
